### ISSUE TITLE
didnt find info on why inf_build folder is getting created in cartridges folder along with other cartridges in sandbox

### ISSUE THREAD

**Issue by praveenprasadn** [jenkinsci/osf-builder-suite-for-sfcc-deploy-plugin#14]
### Describe your use-case which is not covered by existing documentation.

hi i didnt find info on why inf_build folder is getting created in cartridges folder along with other cartridges while uploading to sandbox. please check 2 images for reference. is there any way to avoid automatically creating the inf_build folder? please let me know thanks

**Comment by danechitoaie** [comment]
See here: https://plugins.jenkins.io/osf-builder-suite-for-sfcc-deploy/
It's the "Create Build Info Cartridge". You can set that to `false` and not have it created.

**Comment by praveenprasadn** [comment]
oh great thanks
