### ISSUE TITLE
Missing "Open Commerce API Credentials"! We can't deploy the build without proper credentials, can't we?

### ISSUE THREAD

**Issue by Yamini-TWG** [jenkinsci/osf-builder-suite-for-sfcc-deploy-plugin#2]
Hi, 

I am trying to configure Jenkins to deploy cartridges to Salesforce using OSF deploy plugin, I have followed below wiki to create a jenkinsfile, but its failing with the above error https://wiki.jenkins.io/display/JENKINS/OSF+Builder+Suite+For+Salesforce+Commerce+Cloud+Deploy+Plugin
here is my jenkins file

#!/usr/bin/env groovy

properties([
        buildDiscarder(logRotator(numToKeepStr: '20')),
        disableConcurrentBuilds()
])
node('slave name') {

    stage('Checkout code from Git') {
        scmVars = checkout scm
        print "BRANCH ${scmVars.GIT_BRANCH}"
        print "COMMIT ${scmVars.GIT_COMMIT}"
        print "PREVIOUS COMMIT ${scmVars.GIT_PREVIOUS_COMMIT}"
    }
    stage('build') {
        sh "cd storefront-reference-architecture && npm ci && npm run compile:js && npm run compile:scss"
    }
    stage ('deploy') {
        osfBuilderSuiteForSFCCDeploy(
                hostname: "<hostaname>",
                bmCredentialsId: "d5564126854d51-b1b9-c57d01307dc4",
                OCAPICredentialsId: "b487485-1dff-47cf-8364-6e0f09aceafe",
                buildVersion: "dev",
                createBuildInfoCartridge: true,
                sourcePaths: [
                        [sourcePath: "store/cartridges"]
                ],
                actuvateBuild: true,
                tempDirectory: 'tmp/build'
        )
    }
}

ERROR: Missing "Open Commerce API Credentials"! We can't deploy the build without proper credentials, can't we?
Finished: FAILURE

even I gave the OCAPI credentials it's throwing error saying "it couldn't find one" and I am wondering how can I mention the ocapi version number in jenkins file. 

Any suggertions on how to fix this ?

Thank you

**Comment by danechitoaie** [comment]
I see you used `OCAPICredentialsId`. That's not the correct name for the param. It should be `ocCredentialsId`.

Here's an example for the Deploy and Data Import plugins with the options that are available and need to be configured.

```
    stage('CodePush') {
        osfBuilderSuiteForSFCCDeploy(
            hostname: '<INSTANCE_HOSTNAME>',
            bmCredentialsId: '<CREDENTIALS_ID_OF_TYPE_BUSINESS_MANAGER>',
            tfCredentialsId: '',
            ocCredentialsId: '<CREDENTIALS_ID_OF_TYPE_OPEN_COMMERCE_API>',
            ocVersion: 'v18_6',
            buildVersion: 'dev',
            sourcePaths: [[sourcePath: 'scm/<REPO_USER>/<REPO_NAME>/cartridges']],
            activateBuild: true,
            createBuildInfoCartridge: true,
            tempDirectory: 'tmp/code'
        )
    }

    stage('DataPush') {
        osfBuilderSuiteForSFCCDataImport(
            hostname: '<INSTANCE_HOSTNAME>',
            bmCredentialsId: '<CREDENTIALS_ID_OF_TYPE_BUSINESS_MANAGER>',
            tfCredentialsId: '',
            ocCredentialsId: '<CREDENTIALS_ID_OF_TYPE_OPEN_COMMERCE_API>',
            ocVersion: 'v18_6',
            archiveName: 'metadata',
            sourcePath: 'scm/<REPO_USER>/<REPO_NAME>/metadata',
            importStrategy: 'DELTA',
            tempDirectory: 'tmp/data'
        )
    }
```

**Comment by Yamini-TWG** [comment]
Thank you, it worked. 
I quickly like to understand how can I overwrite the version   buildVersion
1. when I give build version as dev - it is assigning the version as 
b34_20190624_dev
Can I overwrite it, my requirement is dev_yyyymmdd.buildnumber or dev_${some environment variable}

Thank you, 

--

**Comment by danechitoaie** [comment]
Hi,
You can customize what's get appended to the build version but the `bNR_YYYYMMDD_` is always added as prefix. So you can only customize what gets added after this. environment variables are supported `${env.SOMETHING}` but only appended to that `bNR_YYYYMMDD_` part.

**Comment by Yamini-TWG** [comment]
Thank you so much, it worked the way I wanted.
