### ISSUE TITLE
Unable to Create New Code Version with 2FA

### ISSUE THREAD

**Issue by davidlinke** [jenkinsci/osf-builder-suite-for-sfcc-deploy-plugin#5]
Hi,

I am trying to set up Jenkins to use a certificate to push to staging but am getting the following error:

```
[+] Creating new code version
 - cert.staging.webstore.____.demandware.net (b5_20200206_staging)
Failed to create the new code version! 403 - Forbidden!
Response={"_v":"19.10","fault":{"arguments":{"method":"PUT","path":"/data/v19_10/code_versions/b5_20200206_staging"},"type":"ClientAccessForbiddenException","message":"Access to resource 'PUT /data/v19_10/code_versions/b5_20200206_staging' isn't allowed for the current client."}}
```

I have configured the Two Factor Auth credentials according to the post at the bottom of https://xchange.demandware.com/docs/DOC-44159#start=25

I have also whitelisted cert.staging.webstore.____.demandware.net per the readme (with our domain where the ___ is).

Any idea what is causing the error? I am able to push to development just fine without a certificate.

Thanks,
David

**Comment by danechitoaie** [comment]
Hi,
See the README file from this repo - https://github.com/jenkinsci/osf-builder-suite-for-sfcc-deploy-plugin/blob/master/README.md

Looks like you are missing the OCAPI configuration https://github.com/jenkinsci/osf-builder-suite-for-sfcc-deploy-plugin/blob/master/README.md#open-commerceapisettings

And make sure you use a real OCAPI client ID/password and not the default demo aaaaaaaa... one (for security purpose).

**Comment by davidlinke** [comment]
Thanks Dan, you are absolutely right; I forgot to add the OCAPI and webdav configuration to staging. Thanks for your help! Everything seems to be working great now.

**Comment by paramosr** [comment]
Hi, I am having the same isue but I have already configure de OCAPI and WevDAV.
Any idea what could be the error?
I'm able to deploy in development without certificate.
What I'm thinkin is that maybe Im introducing the certificate on jenkins on a wrong way.

![image](https://user-images.githubusercontent.com/60689893/111665014-a725e700-8812-11eb-98f0-b276cd8b58ee.png)


On server Certificate I have a server .crt file pasted.
On client Certificate I have pasted a .pem file.
On client Private Key I have the private key (.key) for the client certificate.

Do you all know if it is correct?

Thanks a lot
Pablo.

**Comment by danechitoaie** [comment]
> On server Certificate I have a server .crt file pasted.
> On client Certificate I have pasted a .pem file.
> On client Private Key I have the private key (.key) for the client certificate.

Yes, this is correct. Anyway if it would've been related to the certs you would've gotten a different error something about certs. 

If you're getting the `403 - Forbidden` error then it's past the cert stuff as it was already able to connect to the server and it seems to be a permission issue. I would still bet on something related to OCAPI/webdav configs but I can't be sure as I don't know how things are configured.

**Comment by paramosr** [comment]
Thanks for the answer.
I thought that it would be some OCAPI/webdav staff but I don't think because I got the same configuration that in development environment, and there I dont have any access problem.
We have a proxy behind the osf builder, maybe could be something in related with that?

Thanks again
Pablo

**Comment by danechitoaie** [comment]
Is the proxy being used when connecting to the development instance as well?
