### ISSUE TITLE
timing out

### ISSUE THREAD

**Issue by gdbtheboss** [jenkinsci/osf-builder-suite-for-sfcc-deploy-plugin#9]
Jenkins version 2.222.3
OSF version : 1.0.8

Hi, Can any one help me figuring out this issue? When we run the build the cartridges (code deployment) are uploading to staging environment cert.staging.web.customer.demandware.net about 70 percent and then timing out. This has been working for years without any issues, May 18th was last successful build and since last week we are seeing this issue. Any help on this would be greatly appreciated.

ERROR: Exception thrown while making HTTP request!
org.apache.http.conn.HttpHostConnectException: Connect to cert.staging.web.customer.demandware.net:443 [cert.staging.web.customer.demandware.net/IP] failed: Connection timed out (Connection timed out)

Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
Thanks
Dilli

**Comment by danechitoaie** [comment]
Hi,
Does this happen on different instance? Or only on staging?
But, since this is a "Connection timed out" type of error it can only mean that it's a server issue. You would need to create a support ticket with SFCC to investigate.

**Comment by gdbtheboss** [comment]
Daniel,

Thanks for your reply. Typically we do the build in staging environment
only. I did open the ticket and they said the OSF has been maintained by
the different communities and I need to contact them. Has this something
happened in the past to any one using Jenkins/OSF?

Thanks
Dilli

**Comment by danechitoaie** [comment]
Yes, I've had people with similar issue and the issue was on the server side. They (SFCC support) need to understand that your issue is not with the plugin (for that I can offer support if there's anything wrong with it) but with their server, as their server times out when the build is being pushed. At that moment all that the plugin is doing is making a PUT request to upload the ZIP, then a POST request to tell SFCC server to unzip the cartridge, and then a DELETE request to delete the ZIP.
So if the server is not able to respond in a timely manner, is not able to process that request then the request times out.

Just for testing purposes you can try to deploy same code on different instance, like a sandbox or development instance and see if there it works or if you have same issue. This way you can isolate that the issue is related to staging only or not.

**Comment by gdbtheboss** [comment]
Thanks Daniel, I will try pushing it to different environment and see if it happens.

**Comment by danechitoaie** [comment]
Also I see that you are on version `1.0.8`? Latest version is `1.1.6` https://plugins.jenkins.io/osf-builder-suite-for-sfcc-deploy/  so I would recommend to update it. Lots of things have changed since 1.0.8

**Comment by gdbtheboss** [comment]
Sure, as soon as I figured this issue I am planning to upgrade. 
Thanks

**Comment by gdbtheboss** [comment]
Hi, The issue is due to the firewall policy on our side, we fixed it and it worked but I would like to proceed with the upgrade. Do you have the link where I can follow step1, step2 ,etc from where we are? Thanks for the support.

**Comment by Rohith13** [comment]
Glad that you have figured out Dilli. I have asked you to check the IP whether it's whitelisted couple of times at your end as that's the exception which we are seeing: 

```
ERROR: Exception thrown while making HTTP request!
org.apache.http.conn.HttpHostConnectException: Connect to cert.staging.web.ethanallen.demandware.net:443 [**cert.staging.web.ethanallen.demandware.net/13.110.101.83**] failed: Connection timed out (Connection timed out)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	
```
Anyways, finally the issue got resolved. :)

**Comment by danechitoaie** [comment]
@Rohith13 thanks for the info. It's always hard to debug these kind of errors specially when additional firewalls are involved as I have no idea what systems are between the client and the server in all these various scenarios.

**Comment by danechitoaie** [comment]
@gdbtheboss You can update the plugins from your Jenkins instance. The update process should be very easy.

1. Go to `Manage Jenkins`
<img width="330" alt="Screen Shot 2021-06-10 at 10 50 18" src="https://user-images.githubusercontent.com/10779010/121486535-e4e17880-c9d9-11eb-946c-e7c9f9f1e670.png">

2. Go to `Manage Plugins`
<img width="1424" alt="Screen Shot 2021-06-10 at 10 50 30" src="https://user-images.githubusercontent.com/10779010/121486604-f591ee80-c9d9-11eb-8ebe-dc0672f6637c.png">

3. Go to `Updates` tab
<img width="783" alt="Screen Shot 2021-06-10 at 10 50 48" src="https://user-images.githubusercontent.com/10779010/121486689-080c2800-c9da-11eb-8c3c-6eba60a9ccda.png">

Here you should be able to see all the updates available for your plugins. And you can update them from there. 

After you update osf-builder-suite-for-sfcc-deploy-plugin review the documentation here  https://plugins.jenkins.io/osf-builder-suite-for-sfcc-deploy/ in case you need to adjust some settings. The latest version deploys the code only with OCAPI credenitals. It no longer requires a BM user/pass. So you might need to setup some webdav and ocapi permissions in BM. The settings are described in the link I pasted above.

**Comment by gdbtheboss** [comment]
Thanks so much Daniel. I will follow this instruction. Do you want me to close this ticket or keep open till I complete the upgrade?

**Comment by danechitoaie** [comment]
We can keep it open until you upgrade in case you have other issues.

**Comment by gdbtheboss** [comment]
Daniel, I did update the jenkins and OSF plugin. While I am plugging in the values, I see OCAPI client id and created that for staging build and added that as well along with other existing clients. Now the next data is OCAPI version, do you know where can I find that in the system?

Thanks
Dilli

**Comment by gdbtheboss** [comment]
is it v21_6?

**Comment by danechitoaie** [comment]
Yes

**Comment by gdbtheboss** [comment]
Thanks so much for your help Daniel. I am able to run the build with the upgraded version.
